### ISSUE TITLE
Add output file option for convert_mt_to_csv.py.

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#10]
For testing purposes, please add the output parameter (`-o OUTPUTFILE`) to `convert_mt_to_csv.py` (previously `mt_dump.py`). Currently it dumps into the standard output.

**Comment by d-a-t-a-d-i-t** [comment]
Well, the current output in its form is just a more human-readable text dump.
Should the output file include this kind of text or a real [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) formatted text?

**Comment by kenorb** [comment]
Yes, if you can output into similar format as the other script doing that, currently it's doing blank spaces, so I believe we need just commas and this extra option.

**Comment by kenorb** [comment]
However commas are not necessary, as long we output plain text, I just need it for testing purposes to do something like:

    find . -name "*.hst" -execdir python3 $CMD -i {} -f fxt4 -o {}.csv

as part of the testing, then compare number of rows between original CSV file and output.

**Comment by aconz2** [comment]
Do you have any `hst` files for testing?

**Comment by kenorb** [comment]
@aconz2  They're generated as in Makefile (`make test`), which doesn't work yet (#12), but check the commands in it (`dl_bt_dukascopy.py` to generate csv, then `convert_csv_to_mt.py` to generate `hst` files).

**Comment by kenorb** [comment]
Fixed in #15
