### ISSUE TITLE
how usage stream candles ?

### ISSUE THREAD

**Issue by rahmangunawans** [FX31337/FX-BT-Scripts#112]
please i need example :(.

**Comment by kenorb** [comment]
Which script you're referring to?

**Comment by rahmangunawans** [comment]
> Which script you're referring to? Can you elaborate?

from iqoptionapi.stable_api import IQ_Option
iq=IQ_Option("", "")
def start_price_stream(symbol,timeframe):
    timeframe = (timeframe)
    iq.start_candles_stream(symbol,int(timeframe),1)
    time.sleep(0.5)
    vela = iq.get_realtime_candles(symbol,int(timeframe))
    for velas in  list(vela):
            date = vela[velas]["from"]
            open = vela[velas]["open"]
            high = vela[velas]["max"]
            low = vela[velas]["min"]
            close = vela[velas]["close"]
            volume = vela[velas]["volume"]
            data = [ date, open,  high,  low,  close]

            df = pd.DataFrame ([data], columns = ['date','open','high','low','close'])
        
            main = df.set_index(['date'])
            main.index = pd.to_datetime(main.index, unit='s')
            #print(symbol)
        return data
        
      with output hst streaming tick.
      
      please  i need output hst.
      for simple example.

**Comment by kenorb** [comment]
> with output hst streaming tick.

HST format is for historical candle data, for ticks you need to use FXT format. Unless you mean candles, not ticks.
