### ISSUE TITLE
Can't Ctrl-C when Python script is busy.

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#13]
File: `convert_csv_to_mt.py`

When there is a long conversion, I can't stop the script by pressing Ctrl-C, something is blocking it.

The workaround is to do: Ctrl-Z, then `kill %1`. So I believe something is wrong.

**Comment by d-a-t-a-d-i-t** [comment]
[Fixed.](https://github.com/d-a-t-a-d-i-t/FX-BT-Scripts/commit/488cf2f5db76608f4c85a07c540b4b7e4cbc8198)
