### ISSUE TITLE
We need requirements.txt with required pip packages.

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#16]
Currently on Debian `./dl_bt_dukascopy.py --help` fails with:

> ImportError: No module named lzma

We need to have `requirements.txt` with required pip packages which can be installed via `pip3` automatically.

This can be generated via:

    pip3 freeze | grep lzma > requirements.txt

Then installed via:

    pip3 -r requirements.txt

Tested, but it doesn't work as expected.

**Comment by d-a-t-a-d-i-t** [comment]
On which Debian version have you tried it?

**Comment by d-a-t-a-d-i-t** [comment]
Python LZMA backport was installed, `dl_bt_dukascopy.py` was updated, test was passed.

**Comment by kenorb** [comment]
Fixed by installing https://github.com/peterjc/backports.lzma which is backport of lzma into Python 3.2, where it's normally available in 3.3.
