### ISSUE TITLE
dl_bt_dukascopy.py: CSV file is not always generated.

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#2]
Testing command:

    ./dl_bt_dukascopy.py -y 2014 -p EURUSD -c

on the existing folder with already existing files.

Problem:
- the CSV file is not generated for every file.

Log:

	Converting into CSV (download/EURUSD/2014-02-14--19h_ticks.csv)...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/02/14/20h_ticks.bi5 into: download/EURUSD/2014-02-14--20h_ticks.bi5...
	Converting into CSV (download/EURUSD/2014-02-14--20h_ticks.csv)...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/02/14/21h_ticks.bi5 into: download/EURUSD/2014-02-14--21h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/02/14/22h_ticks.bi5 into: download/EURUSD/2014-02-14--22h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/02/14/23h_ticks.bi5 into: download/EURUSD/2014-02-14--23h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/02/15/00h_ticks.bi5 into: download/EURUSD/2014-02-15--00h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/02/15/01h_ticks.bi5 into: download/EURUSD/2014-02-15--01h_ticks.bi5...

	Converting into CSV (download/EURUSD/2014-04-09--19h_ticks.csv)...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/09/20h_ticks.bi5 into: download/EURUSD/2014-04-09--20h_ticks.bi5...
	Converting into CSV (download/EURUSD/2014-04-09--20h_ticks.csv)...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/09/21h_ticks.bi5 into: download/EURUSD/2014-04-09--21h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/09/22h_ticks.bi5 into: download/EURUSD/2014-04-09--22h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/09/23h_ticks.bi5 into: download/EURUSD/2014-04-09--23h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/10/00h_ticks.bi5 into: download/EURUSD/2014-04-10--00h_ticks.bi5...
	...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/11/18h_ticks.bi5 into: download/EURUSD/2014-04-11--18h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/11/19h_ticks.bi5 into: download/EURUSD/2014-04-11--19h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/11/20h_ticks.bi5 into: download/EURUSD/2014-04-11--20h_ticks.bi5...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/11/21h_ticks.bi5 into: download/EURUSD/2014-04-11--21h_ticks.bi5...
	Converting into CSV (download/EURUSD/2014-04-11--21h_ticks.csv)...
	Downloading http://www.dukascopy.com/datafeed/EURUSD/2014/04/11/22h_ticks.bi5 into: download/EURUSD/2014-04-11--22h_ticks.bi5...
	Converting into CSV (download/EURUSD/2014-04-11--22h_ticks.csv)...

When the file is not generated, you can see `Downloading` few times in a row (without `Converting` line).

	$ find . -name 2014-04-25\*
	./download/EURUSD/2014-04-25--00h_ticks.bi5
	./download/EURUSD/2014-04-25--01h_ticks.bi5
	./download/EURUSD/2014-04-25--02h_ticks.bi5
	./download/EURUSD/2014-04-25--03h_ticks.bi5
	./download/EURUSD/2014-04-25--04h_ticks.bi5
	./download/EURUSD/2014-04-25--05h_ticks.bi5
	./download/EURUSD/2014-04-25--06h_ticks.bi5
	./download/EURUSD/2014-04-25--07h_ticks.bi5
	./download/EURUSD/2014-04-25--08h_ticks.bi5
	./download/EURUSD/2014-04-25--09h_ticks.bi5
	./download/EURUSD/2014-04-25--10h_ticks.bi5
	./download/EURUSD/2014-04-25--11h_ticks.bi5
	./download/EURUSD/2014-04-25--12h_ticks.bi5
	./download/EURUSD/2014-04-25--13h_ticks.bi5
	./download/EURUSD/2014-04-25--14h_ticks.bi5
	./download/EURUSD/2014-04-25--15h_ticks.bi5
	./download/EURUSD/2014-04-25--16h_ticks.bi5
	./download/EURUSD/2014-04-25--17h_ticks.bi5
	./download/EURUSD/2014-04-25--18h_ticks.bi5
	./download/EURUSD/2014-04-25--19h_ticks.bi5
	./download/EURUSD/2014-04-25--20h_ticks.bi5
	./download/EURUSD/2014-04-25--21h_ticks.bi5
	./download/EURUSD/2014-04-25--21h_ticks.csv
	./download/EURUSD/2014-04-25--22h_ticks.bi5
	./download/EURUSD/2014-04-25--22h_ticks.csv
	./download/EURUSD/2014-04-25--23h_ticks.bi5
	./download/EURUSD/2014-04-25--23h_ticks.csv

--
[![Become a Bounty Hunter](https://www.bountysource.com/badge/issue?issue_id=26472268)](https://www.bountysource.com/issues/26472268)

**Comment by juanj** [comment]
This isn't a bug, at least on your part of the code.
This happens because the downloaded ticks.bi5 of that date/hour is empty.

If you download that data from the "Historical Data Feed" you may notice that data is missing:
![captura de pantalla 2015-09-05 a las 4 12 09 p m](https://cloud.githubusercontent.com/assets/1958175/9701321/316bbafc-53e9-11e5-939d-c8844a739f83.png)
(In the image the data start at 21h. 00h to 20h are omitted)

**Comment by kenorb** [comment]
@juanj Thank you for the explanation. I think you're right, let me double check that tomorrow. If that's the case, how do I send you bounty (as I'm using this first time, and I wasn't expect so quick reply), as I don't see any option to do that?

**Comment by kenorb** [comment]
@juanj Or can you actually add any message that indicates that the dataset is empty, to avoid confusion?

**Comment by juanj** [comment]
I am new at this too.
You have to mark this issue as closed so then i can claim the bounty.

**Comment by kenorb** [comment]
Fixed.
