### ISSUE TITLE
convert_csv_to_mt.py takes ages to convert the data [$50]

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#37]
Currently conversion of CSV data from only one year (800M) into tick data format takes around 1 hour to complete (for all timeframes).

This makes fails for CI builds, because timeout of 30 minutes being reached in order to convert the data from [here](https://github.com/FX31337/FX-BT-Data-EURUSD-DS/tree/EURUSD-2015). [This one](https://travis-ci.org/FX31337/FX-BT-Data-EURUSD-DS/builds/118761747) failed after maximum time of 50 minutes.

Testing:

    git clone --single-branch --branch EURUSD-2014 https://github.com/FX31337/FX-BT-Data-EURUSD-DS.git
    cd FX*
    curl -o Makefile https://raw.githubusercontent.com/FX31337/FX-BT-Data-Test/master/Makefile
    time make

I didn't count, but it's ~3h on MBP (OS X).

The goal is to reduce the conversion time of the data mentioned above, so it completes in reasonable time (e.g. less than half an hour if that's achievable, otherwise max. 50 min), so CI won't fail (max time is [50 minutes](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts)).

File: `convert_csv_to_mt.py`

Test: 

    $ time make
    ...
	Done.

	real	187m37.007s
	user	185m2.853s
	sys	1m7.004s

which makes ~3.11h

--

Result files:

	-rw-r--r--  1 kenorb 4.7M Mar 29 11:35 EURUSD1.hst.gz
	-rw-r--r--  1 kenorb 2.0K Mar 29 12:43 EURUSD10080.hst.gz
	-rw-r--r--  1 kenorb  80M Mar 29 14:19 EURUSD10080_0.fxt.gz
	-rw-r--r--  1 kenorb 9.8K Mar 29 12:34 EURUSD1440.hst.gz
	-rw-r--r--  1 kenorb  80M Mar 29 14:09 EURUSD1440_0.fxt.gz
	-rw-r--r--  1 kenorb 477K Mar 29 11:55 EURUSD15.hst.gz
	-rw-r--r--  1 kenorb  83M Mar 29 13:25 EURUSD15_0.fxt.gz
	-rw-r--r--  1 kenorb  90M Mar 29 13:04 EURUSD1_0.fxt.gz
	-rw-r--r--  1 kenorb  40K Mar 29 12:24 EURUSD240.hst.gz
	-rw-r--r--  1 kenorb  80M Mar 29 13:58 EURUSD240_0.fxt.gz
	-rw-r--r--  1 kenorb 257K Mar 29 12:04 EURUSD30.hst.gz
	-rw-r--r--  1 kenorb  82M Mar 29 13:36 EURUSD30_0.fxt.gz
	-rw-r--r--  1 kenorb  597 Mar 29 12:53 EURUSD43200.hst.gz
	-rw-r--r--  1 kenorb  80M Mar 29 14:30 EURUSD43200_0.fxt.gz
	-rw-r--r--  1 kenorb 1.3M Mar 29 11:45 EURUSD5.hst.gz
	-rw-r--r--  1 kenorb  86M Mar 29 13:15 EURUSD5_0.fxt.gz
	-rw-r--r--  1 kenorb 139K Mar 29 12:14 EURUSD60.hst.gz
	-rw-r--r--  1 kenorb  81M Mar 29 13:47 EURUSD60_0.fxt.gz

**Comment by Kostafun** [comment]
LemonBoy sorry I did not see in Bountysource that you are already working on a solution. Mine solve it from different angle, we can combine both, after some research I see I should rewrite mine to use numpy.memmap instead of in memory list - as with my current solution it may raise out of memory errors on extra large input files or low memory systems.

**Comment by LemonBoy** [comment]
One of the conversion routines collapses the whole set of csv files into a single one, I doubt it's a wise idea to abuse the memory so much (also, Travis might not like that memory usage :).
The profiler shows that the hottest points are the place where the string is split and the timestamp parsing, the latter has been optimized as much as I could and the former is quite optimized by itself.
A two-fold speedup when executed on a beefy machine could be enough to stay under the 50m mark

**Comment by Kostafun** [comment]
Would be best to combine our solutions - your optimization of timestamp parsing and mine parsing timestamp only once (not once per timeframe like before) . I also wonder about memory usage, it may become a problem only with even larger input files. Best would be to parse input file once and store parsed results in  numpy.memmap temporary file . I will finish this solution tomorrow.

**Comment by kenorb** [comment]
@LemonBoy I think something got broken as I've 3 minutes and the data isn't right (too small).

	test/FX-BT-Data-EURUSD-DS $ time make
	+ which gxargs xargs
	+ head -n1
	+ find EURUSD -maxdepth 0
	+ cd EURUSD
	+ find 2014 -type d -maxdepth 0
	+ du -sb EURUSD
	+ cut -f1
	convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f hst4
	+ convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f hst4
	[INFO] Input file: all.csv
	[INFO] Symbol name: EURUSD
	[INFO] Timeframe: M1,M5,M15,M30,H1,H4,D1,W1,MN - [1, 5, 15, 30, 60, 240, 1440, 10080, 43200] minute(s)
	[INFO] Spread: 20
	[INFO] Output directory: .
	[INFO] Server name: default
	[INFO] Output format: hst4
	[INFO] Trying to read data from all.csv...
	gzip -v *.hst
	+ gzip -v EURUSD1.hst EURUSD10080.hst EURUSD1440.hst EURUSD15.hst EURUSD240.hst EURUSD30.hst EURUSD43200.hst EURUSD5.hst EURUSD60.hst
	EURUSD1.hst:	  -99.9% -- replaced with EURUSD1.hst.gz
	EURUSD10080.hst:	  -99.9% -- replaced with EURUSD10080.hst.gz
	EURUSD1440.hst:	  -99.9% -- replaced with EURUSD1440.hst.gz
	EURUSD15.hst:	  -99.9% -- replaced with EURUSD15.hst.gz
	EURUSD240.hst:	  -99.9% -- replaced with EURUSD240.hst.gz
	EURUSD30.hst:	  -99.9% -- replaced with EURUSD30.hst.gz
	EURUSD43200.hst:	  -99.9% -- replaced with EURUSD43200.hst.gz
	EURUSD5.hst:	  -99.9% -- replaced with EURUSD5.hst.gz
	EURUSD60.hst:	  -99.9% -- replaced with EURUSD60.hst.gz
	convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f fxt4
	+ convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f fxt4
	[INFO] Input file: all.csv
	[INFO] Symbol name: EURUSD
	[INFO] Timeframe: M1,M5,M15,M30,H1,H4,D1,W1,MN - [1, 5, 15, 30, 60, 240, 1440, 10080, 43200] minute(s)
	[INFO] Spread: 20
	[INFO] Output directory: .
	[INFO] Server name: default
	[INFO] Output format: fxt4
	[INFO] Trying to read data from all.csv...
	gzip -v *.fxt
	+ gzip -v EURUSD10080_0.fxt EURUSD1440_0.fxt EURUSD15_0.fxt EURUSD1_0.fxt EURUSD240_0.fxt EURUSD30_0.fxt EURUSD43200_0.fxt EURUSD5_0.fxt EURUSD60_0.fxt
	EURUSD10080_0.fxt:	  -99.9% -- replaced with EURUSD10080_0.fxt.gz
	EURUSD1440_0.fxt:	  -99.9% -- replaced with EURUSD1440_0.fxt.gz
	EURUSD15_0.fxt:	  -99.9% -- replaced with EURUSD15_0.fxt.gz
	EURUSD1_0.fxt:	  -99.9% -- replaced with EURUSD1_0.fxt.gz
	EURUSD240_0.fxt:	  -99.9% -- replaced with EURUSD240_0.fxt.gz
	EURUSD30_0.fxt:	  -99.9% -- replaced with EURUSD30_0.fxt.gz
	EURUSD43200_0.fxt:	  -99.9% -- replaced with EURUSD43200_0.fxt.gz
	EURUSD5_0.fxt:	  -99.9% -- replaced with EURUSD5_0.fxt.gz
	EURUSD60_0.fxt:	  -99.9% -- replaced with EURUSD60_0.fxt.gz
	git tag
	+ git tag
	2014
	+ echo Done.
	Done.

	real	3m25.655s
	user	3m22.522s
	sys	0m1.517s
	
	test/FX-BT-Data-EURUSD-DS $ ll *.gz
	-rw-r--r-- 1 kenorb 32 Mar 29 11:16 EURUSD1.hst.gz
	-rw-r--r-- 1 kenorb 36 Mar 29 11:16 EURUSD10080.hst.gz
	-rw-r--r-- 1 kenorb 38 Mar 29 11:18 EURUSD10080_0.fxt.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:16 EURUSD1440.hst.gz
	-rw-r--r-- 1 kenorb 37 Mar 29 11:18 EURUSD1440_0.fxt.gz
	-rw-r--r-- 1 kenorb 33 Mar 29 11:16 EURUSD15.hst.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:18 EURUSD15_0.fxt.gz
	-rw-r--r-- 1 kenorb 34 Mar 29 11:18 EURUSD1_0.fxt.gz
	-rw-r--r-- 1 kenorb 34 Mar 29 11:16 EURUSD240.hst.gz
	-rw-r--r-- 1 kenorb 36 Mar 29 11:18 EURUSD240_0.fxt.gz
	-rw-r--r-- 1 kenorb 33 Mar 29 11:16 EURUSD30.hst.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:18 EURUSD30_0.fxt.gz
	-rw-r--r-- 1 kenorb 36 Mar 29 11:16 EURUSD43200.hst.gz
	-rw-r--r-- 1 kenorb 38 Mar 29 11:18 EURUSD43200_0.fxt.gz
	-rw-r--r-- 1 kenorb 32 Mar 29 11:16 EURUSD5.hst.gz
	-rw-r--r-- 1 kenorb 34 Mar 29 11:18 EURUSD5_0.fxt.gz
	-rw-r--r-- 1 kenorb 33 Mar 29 11:16 EURUSD60.hst.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:18 EURUSD60_0.fxt.gz

It looks like it's failing silently.

**Comment by kenorb** [comment]
Tested PR #51, full conversion from 3h dropped to 45 minutes. I'll do some further testing on CI after merge.

**Comment by kenorb** [comment]
@Kostafun [CI build fails](https://travis-ci.org/FX31337/FX-BT-Data-EURUSD-DS/builds/118761747) on conversion of full year of data with:

> /home/travis/build.sh: fork: Cannot allocate memory

**Comment by kenorb** [comment]
PR #57 introduced different method to prevent out-of-memory issue on CI, having the same timing when comparing reading the file from the memory.
 
Tested process on OS X for both conversion methods as described in the ticket, the completion time was 56 minutes instead of over 3h, giving 3x speed up.

Since 50 minutes still [wasn't enough](https://travis-ci.org/FX31337/FX-BT-Data-EURUSD-DS/builds/119417048) (as exceeded 50min) for both conversions (FXT & HST), so I've split up the test to convert the formats separately, so [HST](https://travis-ci.org/FX31337/FX-BT-Data-EURUSD-DS/jobs/119625909) took 26min and [FXT](https://travis-ci.org/FX31337/FX-BT-Data-EURUSD-DS/jobs/119625912) 41 minutes (for the whole year data), so both tests are passed.

Therefore I'll close the ticket, unless you've anything to add. The bounty would need to be split if that's ok. Plus extra $10 due to some previous confusion. Thanks for your work.

**Comment by LemonBoy** [comment]
The PR #57 reverts the changes introduced by @Kostafun (and it leaves out some print statements since I was lazy, as you can notice from the commit message) and is a simple rebase of the original changeset I proposed.
It uses mmap to read the file in memory to leave some part of the work to the OS, but that's just a marginal speedup, the real one is in the optimized timestamp parser and the more compact pack.
It might be possible to shave some more time by shuffling some code around though.

**Comment by kenorb** [comment]
@LemonBoy For extra $40, can you try to shuffling some more code, please? So ideally both conversions (hst & fxt) are achieved in less than 50min?

**Comment by kenorb** [comment]
@Kostafun Would you like to receive partial bounty for your work? However I'm not sure how the spiting works with bountysource.
