### ISSUE TITLE
Write Python script to read symbols.raw file. [$40]

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#41]
Write a new script in Python 3 which will print the values from `symbols.raw` to the output (similar to `read_symbols_sel.py`).

Can be in any output format, but format of fields should match its type (ask/bid should print float, time should print time, etc).

Related: #33

Format: [`symbols.raw.h`](https://github.com/EA31337/MT-Formats/blob/master/symbols.raw.h).

Sample files: [symbols.raw-samples.zip](https://github.com/FX31337/FX-BT-Scripts/files/190560/symbols.raw-samples.zip)

**Comment by LemonBoy** [comment]
Would you mind if I rename `read_symbols_rel` to `read_symbols` and have it handle both the `rel` and the `raw` format so that most of the code can be shared ?

**Comment by kenorb** [comment]
@LemonBoy Yes, you can. One script dealing with all symbol formats would be great.

**Comment by kenorb** [comment]
Works great. Do you know if it's easy enough to print strings without special characters? E.g. when I pipe the output to `less`, I've got like:

	name = EURUSD^@^@^@^@^@^@
	description = Euro vs US Dollar^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
	altName = ^@^@^@^@^@^@^@^@^@^@^@^@
	baseCurrency = EUR^@^@^@^@^@^@^@^@^@
	group = 0
	digits = 4

**Comment by LemonBoy** [comment]
Good catch, updated :)

**Comment by kenorb** [comment]
Also in one of the altName:

	name = _SP500
	description =
	altName = ^@SP500
	baseCurrency = _SP

**Comment by LemonBoy** [comment]
Hmm, don't think so, the records line up perfectly. Maybe it's a way the program uses to encode some particular records (erased records ?)
