### ISSUE TITLE
Write script to read symgroups.raw file. [$30]

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#42]
Write a new script in Python 3 which will print the values from `symgroups.raw` file to the output (similar to other `read_symbols_x` scripts).

Can be in any output format, but format of fields should match its type (ask/bid should print float, time should print time, etc).

Related: #33, #41

Format reference: [`symgroups.raw.h`](https://github.com/EA31337/MT-Formats/blob/master/symgroups.raw.h)

Check samples files [symgroups.raw-samples.zip](https://github.com/FX31337/FX-BT-Scripts/files/190562/symgroups.raw-samples.zip) or they can be generated by installing [MT4 platform](http://www.metatrader4.com/en/download).

**Comment by kenorb** [comment]
I've this:

	name =
	description = ^@utures
	backgroundColor = 0

	name =
	description = ^@ICEX
	backgroundColor = 0

	name =
	description = ^@TS
	backgroundColor = 0

	name =
	description = ^@PBEX
	backgroundColor = 0

	name =
	description = ^@ong Kong Stock Exchange
	backgroundColor = 0

So looks like it's cut off and name is most of the time empty (if that's correct, that's fine).

Also it's possible that when using with `head` the Exception message won't show?

	$ python3 read_symbols.py -t symgroups -i symgroups.raw | head
    ...

	name = CFD
	description = Contract For Difference
	Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
	BrokenPipeError: [Errno 32] Broken pipe

File: [symgroups.raw](https://github.com/FX31337/FX-BT-Scripts/files/193217/symgroups.raw.zip)

**Comment by LemonBoy** [comment]
Can't do much wrt the leading NULs, the entry's encoded that way into the file...
And I have no problem with `less`, can't say what's wrong there

**Comment by LemonBoy** [comment]
This can no be closed, doesn't it ?

**Comment by kenorb** [comment]
Fixed in #46
