### ISSUE TITLE
New script: dl_bt_metaquotes.py [$130]

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#6]
New script needs to be created: `dl_bt_metaquotes.py` for downloading backtest data (DAT) for given symbol (`-p`) and years (`-y`) from metaquotes.net into given folder (`-d`, e.g. `download/metaquotes/yyyy/mm/`) and convert it to CSV (`-c`), similar to `dl_bt_dukascopy.py`.

Example URL: http://history.metaquotes.net/symbols/EURUSD/list.txt

The script should be fairly similar to: `dl_bt_dukascopy.py`.

Once downloaded, when `-c` option is specified, it should be converted into CSV format (the same format as generated via: `dl_bt_dukascopy.py`). Unfortunately I can't find any documentation on DAT format, possibly could be similar to HST/FXT (see: `convert_mt_to_csv.py`).

**Comment by aconz2** [comment]
The hard part will be figuring out the `dat` byte format. I've taken a brief look at the contents and I think I can figure out the header, but the rest is still a mystery. Can you give some general information on what should be inside? Ie. floats, ints, date and int pairs etc

**Comment by kenorb** [comment]
@aconz2 @d-a-t-a-d-i-t had today look at this as well, mentioned something similar:

> The header is similar to FXT and contains two parts: the first one is from 0x00 to 0x87 (136 Bytes with copyright, symbol period, and some other basic info), the second is from 0x88 to 0x107 (128 Bytes with totally unknown data - though it's the same in every DAT file). ... the compressor algo seems some custom LZW-like.

This should be similar to FXT format (see CSV into FXT conversion in `convert_csv_to_mt.py`, and opposite: `convert_mt_to_csv.py`).

So we expect probably something like:

    2014-01-01 22:00:00    1.37553    1.37553    1.37553    1.37553          1  2014-01-01 22:00:58  4
    2014-01-01 22:00:00    1.37553    1.37553    1.37552    1.37552          1  2014-01-01 22:00:59  4

To make it easier, I believe these DAT files are downloaded by the MT4 platform and should appear in the filesystem, then converted into FXT format.

If you're Windows guy, run the platform, then click menu/History Center, then download the files. If you're Linux guy, check the invitation to repo which I've sent to you, there is working VM with the platform, so when you run `wine terminal.exe` and you've X11 forwarding enabled, it would emulate it.

So I believe the DAT formats are converted automatically by the MT4 platform, once they're downloaded at some point, but I'm looking to automate this process. Either by reading this format, or downloading the files, placing in the platform, then one-time run should convert them into FXT.

The bounty can be higher if you can make the DAT readable, like 100 or above, depending how long it'll take to figure it out.

**Comment by kenorb** [comment]
@aconz2 added some additional info which could be useful

**Comment by aconz2** [comment]
I reached a similar conclusion to @d-a-t-a-d-i-t 
I've run MT4 in wine no problems and having a known CSV output will be very useful on a dataset input.
Autohotkey script could be a possibility but dealing with that would be a pain. I'm going to take a stab at figuring out DAT. Will raise the bounty.

**Comment by kenorb** [comment]
@aconz2 This is what I've got from the source which I don't know if he wants to be published:

> Offs +0x88 contains key[0x80]. +0x108 crypted data by key (xor) and compressed with lzo1x

Could be helpful.

**Comment by aconz2** [comment]
:+1: I had a thought it might be "crypted" with xor, oldest trick in the book

**Comment by kenorb** [comment]
@aconz2 How is going? Did it work, or there are some still issues?

**Comment by aconz2** [comment]
despite having tried every combination of lzo1* and xor then decompress/decompress then xor I haven't gotten it to work.

what would be most helpful is a single dat file and its corresponding csv. I've been unable to import/add a dat file directly into mt4, so I had to download a whole set of dat files and export the combined csv. maybe you have some insight on this?

**Comment by kenorb** [comment]
@aconz2 You can install MT4 on your local, download single DAT file either manually (so in this case you can use single file) or via History Center, and after first run the platform should find the DAT file and convert into HST file (see some previous quotes above), then use `convert_mt_to_csv.py` script to convert it into CSV format.

**Comment by kenorb** [comment]
@aconz2 But based on what you're saying, you already tried that?

**Comment by kenorb** [comment]
@aconz2 You can also try hard way by running terminal with `WINEDEBUG=trace+all`, but I don't think it'll show which lzo1* compression is being used when you fetch the DAT files, unless you want to use `winedbg`. Not sure if this is what you want to try.

**Comment by aconz2** [comment]
Yea, I haven't gotten it to find the DAT file and convert it.
`WINEDEBUG` has given some helpful things to investigate, currently looking into this more. Though MT4 really doesn't like debuggers or traces

**Comment by kenorb** [comment]
@aconz2: Please check the following links which could be helpful:

- [Are there any tools or scripts for identifying compression algorithms in executables?](http://reverseengineering.stackexchange.com/q/1463/12021)
- [Unknown compression algorithm](http://reverseengineering.stackexchange.com/q/6099/12021)
- [Unknown game data compression method](http://reverseengineering.stackexchange.com/q/6527/12021)

for some fresh ideas.

**Comment by kenorb** [comment]
@aconz2

I did some few tests, maybe something would be useful from it:

1. After provisioning VM, I've run `wine terminal.exe` in /opt (I had some windows outside of screen, so I had to remove some values from: `config/terminal.ini `).
1. I've placed DAT file in `./history/FxPro.com-Demo04`, but it didn't work.
1. Deleted old dat and other files: `find . '(' -name "*.dat" -or -name "*.fxt" -or -name "*.hst" ')' -delete`
1. In History Center I've requested download of EURAUD M1, the new DAT files appeared in: `./history/downloads/EURAUD/EURAUD_*.dat` during the download. Possibly placing .dat in this folder, could trigger conversion?
1. I could check the downloading progress via: `sudo strace -fp $(pgrep terminal.exe) -e file 2>&1 | grep history`.
1. At some point new files appeared in (probably after terminal restart): `./history/FxPro.com-Demo04/EURAUD1.hst` and other .hst for different timeframes, but probably not from the DAT files based on the following test: `./convert_mt_to_csv.py -f hst4 -i ../history/FxPro.com-Demo04/AUDJPY1.hst`, but from the latest data as I was connected (see right-bottom corner).
1. I've exported data into .csv file (there is a button: Export). Which can give you idea how CSV looks like. Then removed every row exempt one month (e.g. `2015.09`). But after importing and removing .hst file didn't re-create fresh one. Importing .dat (*.*) doesn't complain about anything, but it doesn't work either.
1. Tested above having created new demo account (you can fill any random data there). You can re-use below:

  ![screen shot 2015-10-05 at 22 15 04](https://cloud.githubusercontent.com/assets/266306/10295047/c7d16d96-6bb5-11e5-8484-d9254ff48a89.png)

1. Did backtest - Strategy Tester (for the dates which were downloaded, but it complained the file is missing).
 
So no idea, but I couldn't force terminal to read/convert DAT files either, maybe emulation doesn't work properly (sometimes it crashes), or there is some missing files or entries in registry (as I'm not using installed version, but a dump).

--

Re-tested similar thing on the version which was installed on OSX (under wine as well) in off-line (No Connection in right-bottom corner), so no extra new data is inserted.

1. Downloaded EURAUD M1 in History Center, then over 140 DAT files appeared in `history/downloads/EURAUD`.
1. `history/downloads/EURAUD/EURAUD1.hst` appeared, with headers but empty (which looks like a placeholder for expected data).
1. Downloaded again or double clicked on EURAUD M1 in History Center, new popup appeared: `There are no new data for a symbol 'EURAUD'. Do you want to recalculate all timeframes?`. Still no luck.

**Comment by kenorb** [comment]
@aconz2 Wrote simple [Python code](http://reverseengineering.stackexchange.com/a/11036/12021). Shouldn't `lzo1x` have some same repeated header if all files have the same key?

    for f in *.dat; { dd if=$f bs=1 status=none skip=$((0x88)) count=$((0x80)) | hexdump -C; }

**Comment by aconz2** [comment]
It should if something like `lzop` was being used, otherwise if its compressed using `lzo1x` as a library, then its not necessary. I wrote some tests in C to try decompressing with each `lzo`* (there are many) but none of them worked.

**Comment by kenorb** [comment]
@aconz2 Can you try `liblzma`? Found the references in the memory dump.

1. Run terminal (start downloading some .dat files to load some context).
1. Take pid: `winedbg --command "info proc"`
1. Make a dump: `winedbg --minidump mt.mdmp $((0x3b))` (where 0x3b is your pid).
1. `strings mt.mdmp` or view the file (in vim search via: `/l.z.m.a`).

**Comment by aconz2** [comment]
Can you post that dump somewhere, having trouble recreating. Have another idea to try but will look at that in the meantime

**Comment by kenorb** [comment]
@aconz2 Check e-mail.

**Comment by mafagafogigante** [comment]
@kenorb Could you tell me anything about convert_dat.py? It is very poorly documented and I don't think I completely understand to what it supposedly converts .dat files to. Thanks.

**Comment by kenorb** [comment]
@mafagafogigante So far it's uncompressing it from LZO into raw format. From there it needs to be converted (32bit Little-Endians such as dates, etc.) into CSV, which is not done.

**Comment by abcht** [comment]
@kenorb I managed to extract exchange rates as follows: 

```
When? 2015-06-30 14:15:00, rate: 1.24831
When? 2015-06-30 14:16:00, rate: 1.24846
When? 2015-06-30 14:38:00, rate: 1.24755
When? 2015-06-30 15:00:00, rate: 1.24745
```

Which obviously I can format as CSV later on. I'm wondering though, what data is supposed to be displayed in columns 3 to 8 in your sample data above?

> 2014-01-01 22:00:00    1.37553    1.37553    1.37553    1.37553          1  2014-01-01 22:00:58  4
> 2014-01-01 22:00:00    1.37553    1.37553    1.37552    1.37552          1  2014-01-01 22:00:59  4

**Comment by abcht** [comment]
Ok I found what I need actually.

**Comment by kenorb** [comment]
Btw. Be aware that what's left (to split) is actually half of the bounty, as the first one was result of `convert_dat.py`, but it wasn't finished yet, that's why the issue is still open.

**Comment by kenorb** [comment]
@neosilky, @abcht Are you still working on that issue?

**Comment by neosilky** [comment]
@kenorb I managed to modify scripts to download what we want + save them. I couldn't manage to convert the data though.

**Comment by kenorb** [comment]
@neosilky Can you send PR with what you got so far? So @d-a-t-a-d-i-t can pick it up, then we can split the bounty.

**Comment by Andrej730** [comment]
I've managed to extract timestamp intervals and some ratio (have no idea what it is) that have very similar value throughout any .dat file. 
Maybe you can help me with it, check my fork - https://github.com/Andrej730/FX-BT-Scripts/

**Comment by kenorb** [comment]
@Andrej730 I think the most difficulty in here was knowing how to decompress dat file (which was done), and 2nd part how the data is structured and stored. It's a bit pity that many people was working at the same time, and didn't register that are working on the solution.

@d-a-t-a-d-i-t sent some PR today where his solution seems to be more complete, as it deals with the data it-self, and reading these values. So these values are not ratio, but open/high/low/close/volume values as shown in other CSV formats/scripts, and they seems to be stored in incremental way.

Let me test these scripts and close the issue when it works.

**Comment by kenorb** [comment]
As per PR: #19
