### ISSUE TITLE
Script to convert CSV into HCC

### ISSUE THREAD

**Issue by kenorb** [FX31337/FX-BT-Scripts#81]
Expand `convert_csv_to_mt.py` script to convert CSV input files into HCC (as implemented as part of GH-77). So `-f` parameter should accept the new `hcc` format (similar as it works for other hst/fxt formats).

codemill$120

**Comment by kenorb** [comment]
@paulohrpinheiro Let me know if you've any questions and you're happy to work on the issue.

**Comment by paulohrpinheiro** [comment]
Hello, Rafal.


The script is already generating the file, I am now finishing the 
writing of the headers (with the offset of the data and the number of 
lines). I also started writing some tests with unittest. For this I had 
to move some parts of the script to functions, so must also check that 
did not cause side effects in the other options. Checking all this, I 
send the PR to you test too. I hope to finish in the maximum tomorrow 
morning (my time now is Mon, 17 Oct 2016 14:18:34 -0200).

Hug, thank you.

--
Paulo Henrique Rodrigues Pinheiro
https://about.me/paulohrpinheiro

Em 17-10-2016 14:11, Rafal escreveu:
